### PR TITLE
Set background and default page colour methods

### PR DESCRIPTION
**Pull request by kmathew-pdftron**

### CODE REVIEW

**Comment by terryyoon-pdftron** [comment]
@sgong-pdftron @JamesTron

**Comment by terryyoon-pdftron** [comment]
@sgong-pdftron @JamesTron

**Comment by ama-pdftron** [comment]
@darrenchann Please review

**Comment by darrenchann** [comment]
```
void showViewer() async {
    // Opening without a config file will have all functionality enabled.
    // await PdftronFlutter.openDocument(_document);

    var config = Config();
    // How to disable functionality:
    //      config.disabledElements = [Buttons.shareButton, Buttons.searchButton];
    //      config.disabledTools = [Tools.annotationCreateLine, Tools.annotationCreateRectangle];
    // Other viewer configurations:
    //      config.multiTabEnabled = true;
    //      config.customHeaders = {'headerName': 'headerValue'};
    await PdftronFlutter.setDefaultPageColor(255,0,0);
```

tried to force default page colour to red, but viewer not changing colour (iOS & Android)
image

**Comment by darrenchann** [comment]
after some configuration fixes can get methods to work:
image
Android (green is default background colour, red is pagecolour)

image
iOS - portrait same colours as indicated in android

**Review by dluco — APPROVED** [review]

**Pull request merged**
